// ponytail: dental service catalog. Edit this single file to add/rename/reorder services.

import { content } from "@/lib/content"

export interface Service {
  slug: string;
  name: string;
  short: string;
  description: string;
  bullets: string[];
  icon: string;
  startingPrice: string;
  category: 'adult' | 'kids';
}

export const services: Service[] = content('SERVICES', [
  // ── ADULT SERVICES ──
  {
    slug: 'root-canal-therapy',
    name: 'Root Canal Therapy',
    short: 'Save your tooth with painless root canal.',
    description: 'Root canal therapy removes infected pulp from inside your tooth, cleans the canal, and seals it to prevent reinfection. Performed under local anaesthesia  -  completely painless.',
    bullets: [
      'Painless procedure under local anaesthesia',
      'Single or multi-visit depending on infection',
      'Done under dental microscope for precision',
      'Followed by crown placement for protection',
      'Post-treatment care guidance provided',
    ],
    icon: 'Tooth',
    startingPrice: '₹3,999',
    category: 'adult',
  },
  {
    slug: 'repeat-root-canal-therapy',
    name: 'Repeat Root Canal',
    short: 'Re-treat failed root canals to save teeth.',
    description: 'If a previously root-canaled tooth gets reinfected, repeat RCT cleans the canals again, removes old filling material, and re-seals. Often done microscopically for best outcomes.',
    bullets: [
      'Removal of existing root canal filling',
      'Microscopic cleaning of complex canals',
      'Disinfection with advanced irrigants',
      'Re-obturation with biocompatible materials',
      'Usually completed in 1-2 sessions',
    ],
    icon: 'Tooth',
    startingPrice: '₹5,999',
    category: 'adult',
  },
  {
    slug: 'surgical-root-canal-therapy',
    name: 'Surgical Root Canal',
    short: 'Surgery for persistent root infections.',
    description: 'When infection persists after conventional RCT, surgical root canal (apicoectomy) removes the tip of the root and seals the canal from the end. A microscopic procedure for complex cases.',
    bullets: [
      'Local anaesthesia  -  completely painless',
      'Microsurgical removal of root tip',
      'Retrograde filling to seal the canal',
      'Minimally invasive with fast recovery',
      'Follow-up x-ray to confirm healing',
    ],
    icon: 'Tooth',
    startingPrice: '₹7,999',
    category: 'adult',
  },
  {
    slug: 'tooth-scaling-cleaning',
    name: 'Scaling & Cleaning',
    short: 'Deep cleaning for healthy gums.',
    description: 'Professional scaling removes plaque, tartar and stains from above and below the gumline. Prevents gum disease, cavities, and bad breath. Recommended every 6 months.',
    bullets: [
      'Ultrasonic scaling for deep tartar removal',
      'Hand scaling for精细 finishing',
      'Polishing for smooth, stain-free surfaces',
      'Fluoride application on request',
      'Oral hygiene tips for maintenance',
    ],
    icon: 'Sparkles',
    startingPrice: '₹999',
    category: 'adult',
  },
  {
    slug: 'contact-free-stain-removal',
    name: 'Stain Removal Care',
    short: 'Remove stains without touching your teeth.',
    description: 'Advanced air-abrasion technology removes stubborn stains without any instrument touching your enamel. Painless, quick, and ideal for stains that brushing alone cannot remove.',
    bullets: [
      'No instruments touch the tooth surface',
      'Effective on coffee, tea, tobacco stains',
      'Single-session procedure',
      'Immediate visible results',
      'Safe on enamel  -  no damage',
    ],
    icon: 'SprayCan',
    startingPrice: '₹1,499',
    category: 'adult',
  },
  {
    slug: 'wisdom-tooth-management',
    name: 'Wisdom Tooth Care',
    short: 'Expert care for your wisdom teeth.',
    description: 'Wisdom teeth often cause pain, crowding, or infection. We assess with x-rays and recommend either management (if salvageable) or atraumatic extraction with minimal recovery time.',
    bullets: [
      'Digital OPG x-ray evaluation',
      'Painless management or extraction',
      'Minimally invasive surgical technique',
      'Post-operative care and medication',
      'Follow-up review for healing',
    ],
    icon: 'Bone',
    startingPrice: '₹3,499',
    category: 'adult',
  },
  {
    slug: 'bioceramic-fillings',
    name: 'BioCeramic Fillings',
    short: 'Fillings that bond with your tooth.',
    description: 'Bioceramic materials are the latest in restorative dentistry  -  they bond chemically with natural tooth structure, release fluoride, and are highly biocompatible. Ideal for deep fillings near the nerve.',
    bullets: [
      'Chemically bonds to natural tooth',
      'Fluoride-releasing  -  prevents recurrence',
      'Bioactive  -  encourages natural repair',
      'Ideal for deep cavities near pulp',
      'Single-visit procedure',
    ],
    icon: 'Gem',
    startingPrice: '₹1,999',
    category: 'adult',
  },
  {
    slug: 'caps-dental-crowns',
    name: 'Dental Crown Work',
    short: 'Restore broken or weak teeth with crowns.',
    description: 'A dental crown (cap) covers and protects a damaged tooth, restoring its shape, size, and function. Available in ceramic, zirconia, and metal-ceramic options matched to your tooth shade.',
    bullets: [
      'Custom-made to match your tooth shade',
      'Ceramic, zirconia, or metal-ceramic options',
      'Protects root-canaled or cracked teeth',
      'Durable  -  lasts 10-15 years with care',
      'Comfortable fit in 2-3 visits',
    ],
    icon: 'Crown',
    startingPrice: '₹4,499',
    category: 'adult',
  },
  {
    slug: 'dental-bridges',
    name: 'Dental Bridge Work',
    short: 'Replace missing teeth with fixed bridges.',
    description: 'A dental bridge literally bridges the gap created by missing teeth. Anchored on adjacent healthy teeth, it restores your smile, bite, and facial structure. Fixed  -  no removal needed.',
    bullets: [
      'Natural-looking ceramic restoration',
      'Fixed  -  no removal or special care',
      'Prevents adjacent teeth from shifting',
      'Restores chewing function fully',
      'Shade-matched to your natural teeth',
    ],
    icon: 'Bridge',
    startingPrice: '₹14,999',
    category: 'adult',
  },
  {
    slug: 'dental-implants',
    name: 'Implant Dentistry',
    short: 'Titanium roots for natural smile.',
    description: 'Dental implants are the gold standard for missing teeth. A titanium post is placed in the jawbone, topped with a ceramic crown. Looks, feels and functions exactly like a natural tooth.',
    bullets: [
      'Titanium post fuses with jawbone',
      'Ceramic crown matched to your teeth',
      'Does not affect adjacent healthy teeth',
      'Prevents bone loss in the jaw',
      'Lifetime durability with proper care',
    ],
    icon: 'Activity',
    startingPrice: '₹24,999',
    category: 'adult',
  },
  {
    slug: 'full-mouth-rehabilitation',
    name: 'Mouth Restoration',
    short: 'Full mouth restoration for damaged teeth.',
    description: 'Full mouth rehabilitation combines implants, crowns, bridges and sometimes dentures to restore an entire mouth. Custom-planned using digital smile design and 3D imaging.',
    bullets: [
      'Comprehensive digital smile design',
      'Multiple implants + prosthetics',
      'Restores bite, chewing and aesthetics',
      'Sedation options for complex cases',
      'Phased treatment plan for affordability',
    ],
    icon: 'Smile',
    startingPrice: '₹1,49,999',
    category: 'adult',
  },
  {
    slug: 'teeth-whitening',
    name: 'Teeth Whitening',
    short: 'Professional bleaching for a brighter smile.',
    description: 'In-office laser teeth whitening uses professional-grade gel activated by a special light. Results are immediate  -  several shades brighter in about an hour. Custom tray option for home use.',
    bullets: [
      'One-session in-office treatment',
      'Up to 8 shades brighter immediately',
      'Laser-activated professional gel',
      'Custom take-home trays available',
      'Minimal sensitivity protocol',
    ],
    icon: 'Sun',
    startingPrice: '₹4,999',
    category: 'adult',
  },
  {
    slug: 'smile-designing',
    name: 'Smile Designing',
    short: 'Smile makeover with veneers.',
    description: 'Digital smile design analyses your facial proportions, lip line, and tooth shape. Using veneers, contouring, crowns or alignment, we craft a smile that fits your face naturally.',
    bullets: [
      'Digital photography and facial analysis',
      'Custom treatment plan preview',
      'Veneers, contouring, or crowns as needed',
      'Shade, shape and proportion optimisation',
      'Mock-up preview before final restorations',
    ],
    icon: 'Shapes',
    startingPrice: '₹14,999',
    category: 'adult',
  },
  {
    slug: 'broken-tooth-management',
    name: 'Broken Tooth Care',
    short: 'Fix for chipped or broken teeth.',
    description: 'Whether from an accident, fall, or biting something hard, a broken tooth needs prompt attention. We assess damage, treat pain, and restore the tooth with bonding, filling or crown.',
    bullets: [
      'Same-day emergency appointments',
      'Pain relief and damage assessment',
      'Composite bonding for minor chips',
      'Crown for major fractures',
      'Root canal if nerve is exposed',
    ],
    icon: 'AlertTriangle',
    startingPrice: '₹1,999',
    category: 'adult',
  },
  {
    slug: 'dental-veneers',
    name: 'Porcelain Veneers',
    short: 'Thin shells that transform your smile.',
    description: 'Veneers are custom-made thin shells bonded to the front of teeth. They fix discolouration, chips, gaps, and mild misalignment. Minimal tooth reduction required  -  maximum aesthetic result.',
    bullets: [
      'Minimal enamel reduction (0.3-0.5mm)',
      'Stain-resistant ceramic material',
      'Natural translucency like real enamel',
      'Fixed in 2-3 visits',
      'Lasts 10-15 years with care',
    ],
    icon: 'Film',
    startingPrice: '₹7,999',
    category: 'adult',
  },
  {
    slug: 'gaps-crowding-correction',
    name: 'Gap & Crowding Fix',
    short: 'Close gaps and align crowded teeth.',
    description: 'Diastema (gaps) and crowding can be corrected with orthodontic braces, clear aligners, or cosmetic bonding  -  depending on severity. We recommend the least invasive option first.',
    bullets: [
      'Orthodontic assessment and digital scan',
      'Braces, aligners, or bonding options',
      'Non-invasive cosmetic closure for small gaps',
      'Predictable timeline with progress tracking',
      'Retainers to maintain results',
    ],
    icon: 'Columns',
    startingPrice: '₹4,999',
    category: 'adult',
  },
  {
    slug: 'non-microscope-dentistry',
    name: 'Basic Dental Care',
    short: 'Quality dental care at affordable prices.',
    description: 'For patients who prefer more affordable treatment, our experienced dentists provide quality care using conventional techniques. Same expertise, same standards, without the microscope surcharge.',
    bullets: [
      'Experienced senior dentists',
      'Quality materials and techniques',
      'More affordable than microscope-assisted',
      'Suitable for straightforward cases',
      'All treatment guarantees apply',
    ],
    icon: 'EyeOff',
    startingPrice: '₹1,499',
    category: 'adult',
  },
  {
    slug: 'tooth-extraction',
    name: 'Tooth Extractions',
    short: 'Gentle removal of damaged teeth.',
    description: 'When a tooth cannot be saved, we perform atraumatic extraction to remove it with minimal discomfort. Simple or surgical extraction depending on the tooth condition.',
    bullets: [
      'Local anaesthesia for painless procedure',
      'Simple or surgical extraction as needed',
      'Minimally traumatic technique',
      'Post-extraction care instructions',
      'Follow-up review for healing',
    ],
    icon: 'Minus',
    startingPrice: '₹1,499',
    category: 'adult',
  },
  {
    slug: 'laser-gum-surgery',
    name: 'Laser Gum Surgery',
    short: 'Laser fix for gum disease.',
    description: 'Diode laser gum surgery treats periodontal disease, reshapes uneven gums, and corrects gummy smile with virtually no bleeding or downtime. Precision without scalpels or stitches.',
    bullets: [
      'No scalpel, minimal bleeding',
      'Treats gum disease and pocket reduction',
      'Gum contouring for gummy smile',
      'Faster healing than conventional surgery',
      'Single or multiple sessions depending on severity',
    ],
    icon: 'Zap',
    startingPrice: '₹3,499',
    category: 'adult',
  },
  {
    slug: 'orthodontics-braces',
    name: 'Braces Treatments',
    short: 'Straighten teeth with metal braces.',
    description: 'Traditional braces remain one of the most effective ways to correct misalignment. Metal, ceramic (tooth-coloured), and self-ligating options available. Suitable for all age groups.',
    bullets: [
      'Metal, ceramic, or self-ligating brackets',
      'Custom treatment plan with digital scan',
      'Regular adjustments every 4-6 weeks',
      'Estimated treatment time 12-24 months',
      'Retainer after treatment completion',
    ],
    icon: 'Grid3X3',
    startingPrice: '₹19,999',
    category: 'adult',
  },
  {
    slug: 'invisalign',
    name: 'Invisalign Aligners',
    short: 'Clear, removable for discreet straightening.',
    description: 'Invisalign uses a series of custom-made clear aligners to shift teeth gradually. Nearly invisible, removable for eating and cleaning, and typically faster than braces for mild to moderate cases.',
    bullets: [
      'Custom 3D-printed clear aligners',
      'Removable  -  eat and clean normally',
      'Nearly invisible appearance',
      'Digital scan  -  no messy impressions',
      'Typical treatment 6-18 months',
    ],
    icon: 'ScanEye',
    startingPrice: '₹44,999',
    category: 'adult',
  },
  {
    slug: 'sleep-dentistry',
    name: 'Sedation Dentistry',
    short: 'Dental treatment under sedation.',
    description: 'Sleep dentistry uses oral sedation or IV sedation so you can undergo multiple procedures in one visit with zero anxiety, memory, or discomfort. Ideal for severe dental phobia or complex treatments.',
    bullets: [
      'Oral or IV sedation options',
      'Complete treatment in one session',
      'No memory of the procedure',
      'Vital signs monitored throughout',
      'Recovery in supervised lounge',
    ],
    icon: 'Moon',
    startingPrice: '₹5,999',
    category: 'adult',
  },

  // ── KIDS SERVICES ──
  {
    slug: 'tooth-colored-fillings-kids',
    name: 'Kids Tooth Fillings',
    short: 'Natural-looking fillings for childrens teeth.',
    description: 'Composite tooth-coloured fillings restore decayed baby teeth and permanent teeth. Matches natural tooth colour, bonds directly to the tooth, and requires minimal drilling.',
    bullets: [
      'Tooth-coloured  -  invisible in the mouth',
      'Bonds directly to the tooth',
      'Minimal drilling required',
      'Single-visit procedure',
      'Child-friendly approach and atmosphere',
    ],
    icon: 'PaintBucket',
    startingPrice: '₹999',
    category: 'kids',
  },
  {
    slug: 'zirconia-crowns-kids',
    name: 'Kids Zirconia Crown',
    short: 'Strong, tooth-coloured caps for milk teeth.',
    description: 'Zirconia crowns for kids are prefabricated ceramic caps that fit over decayed or damaged baby teeth. Metal-free, biocompatible, and available in natural tooth shades.',
    bullets: [
      'Metal-free, completely biocompatible',
      'Natural tooth colour and translucency',
      'Single-visit placement',
      'Strong enough for back teeth',
      'Gentle, child-friendly procedure',
    ],
    icon: 'Crown',
    startingPrice: '₹2,499',
    category: 'kids',
  },
  {
    slug: 'childrens-root-canal',
    name: 'Kids Root Canal',
    short: 'Gentle therapy to save infected baby teeth.',
    description: 'Pulp therapy (baby root canal) removes infected nerve tissue from a childs tooth while preserving the crown. Essential for saving the tooth until the permanent successor erupts naturally.',
    bullets: [
      'Child-friendly, gentle approach',
      'Preserves baby tooth for normal eruption',
      'Relieves pain from deep decay',
      'Single or two-visit procedure',
      'Post-treatment crown for protection',
    ],
    icon: 'Heart',
    startingPrice: '₹1,999',
    category: 'kids',
  },
  {
    slug: 'preventive-dentistry-kids',
    name: 'Kids Dentistry Care',
    short: 'Fluoride and sealants for cavity-free kids.',
    description: 'Preventive dentistry includes professional fluoride application, pit and fissure sealants, and oral hygiene education tailored to children. Builds a foundation for lifelong dental health.',
    bullets: [
      'Fluoride varnish application',
      'Pit and fissure sealants on molars',
      'Diet and brushing guidance for parents',
      'Regular 6-month recall schedule',
      'Early detection of developing issues',
    ],
    icon: 'Shield',
    startingPrice: '₹599',
    category: 'kids',
  },
  {
    slug: 'face-jaw-correction-kids',
    name: 'Kids Jaw Correction',
    short: 'Early jaw correction for growing children.',
    description: 'Functional appliances guide jaw growth in children, correcting underbites, overbites, and narrow arches while the child is still growing. Best results in ages 7-12.',
    bullets: [
      'Non-invasive functional appliances',
      'Corrects bite and jaw alignment early',
      'Guides facial growth for better aesthetics',
      'May simplify or avoid future braces',
      'Best outcomes in growing children 7-12 yrs',
    ],
    icon: 'Orbit',
    startingPrice: '₹14,999',
    category: 'kids',
  },
  {
    slug: 'orthodontics-kids',
    name: 'Kids Orthodontics',
    short: 'Early braces and alignment for children.',
    description: 'Early orthodontic evaluation (age 7+) identifies developing issues. Interceptive treatment with braces or aligners can guide teeth into proper position, preventing complex problems later.',
    bullets: [
      'Early evaluation from age 7',
      'Interceptive treatment for crowding',
      'Space maintenance for missing teeth',
      'Braces or aligners for teens',
      'Shorter treatment time than adult ortho',
    ],
    icon: 'Grid3X3',
    startingPrice: '₹14,999',
    category: 'kids',
  },
  {
    slug: 'aligners-kids-invisalign-first',
    name: 'Kids Teeth Aligners',
    short: 'Clear aligners for growing kids.',
    description: 'Invisalign First is designed for children aged 6-12 with mixed dentition (baby and permanent teeth). Expands arches, guides eruption, and corrects bite issues  -  all with clear, removable aligners.',
    bullets: [
      'Custom-made for mixed dentition',
      'Removable  -  easy brushing and eating',
      'Expands arches and guides eruption',
      'Nearly invisible appearance',
      'Fewer appointments than braces',
    ],
    icon: 'ScanEye',
    startingPrice: '₹34,999',
    category: 'kids',
  },
  {
    slug: 'sleep-dentistry-kids',
    name: 'Kids Sleep Dentist',
    short: 'Gentle sedation for anxious children.',
    description: 'Paediatric sleep dentistry uses safe sedation protocols approved for children. The child remains relaxed throughout the procedure with no memory of it. Ideal for extensive treatment or high anxiety.',
    bullets: [
      'Paediatric-safe sedation protocols',
      'Complete treatment in one visit',
      'No fear, anxiety, or trauma',
      'Monitored by paediatric anaesthetist',
      'Gentle recovery with parental comfort',
    ],
    icon: 'Moon',
    startingPrice: '₹4,999',
    category: 'kids',
  },
])

// 22 adult + 8 kids = 30 services total
// Note: 'tooth-colored-fillings-kids' appears only once (kids category).
// The adult version is not provided since tooth-coloured fillings are primarily
// associated with paediatric dentistry in the Microsmiles portfolio.


export function getService(slug: string): Service | undefined {
  return services.find((s) => s.slug === slug);
}
